-- Schema for DPO Training Registration (Jakarta, 5-6 Mei 2026)

-- Create table for registration submissions
create table pdp_advance_training_registration (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  full_name text not null,
  company_name text not null default 'PT Bussan Auto Finance',
  division_role text not null,
  email text,
  phone_number text
);

-- Enable RLS
alter table pdp_advance_training_registration enable row level security;

-- Allow inserts from anon and authenticated
create policy "Enable insert for everyone" on pdp_advance_training_registration for insert with check (true);

-- Allow select only for authenticated (if needed)
create policy "Enable read access for authenticated users only" on pdp_advance_training_registration for select using (auth.role() = 'authenticated');

-- The rate_limit_tokens and submission_logs tables should already exist if they are sharing the same database.
-- If not, here are the table definitions you need:

/*
create table rate_limit_tokens (
    id uuid default gen_random_uuid() primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    token text not null unique,
    ip_address text,
    used boolean default false,
    expires_at timestamp with time zone not null
);

create table submission_logs (
    id bigint generated by default as identity primary key,
    ip_address text,
    submitted_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table rate_limit_tokens enable row level security;
alter table submission_logs enable row level security;
create policy "Enable all access for service role" on rate_limit_tokens for all using (auth.role() = 'service_role');
create policy "Enable all access for service role" on submission_logs for all using (auth.role() = 'service_role');
*/
